/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst";
export {};
declare module "sst" {
    export interface Resource {
        LOGTO_CLIENT_ID: {
            type: "sst.sst.Secret";
            value: string;
        };
        LOGTO_CLIENT_SECRET: {
            type: "sst.sst.Secret";
            value: string;
        };
        LOGTO_M2M_ID: {
            type: "sst.sst.Secret";
            value: string;
        };
        LOGTO_M2M_SECRET: {
            type: "sst.sst.Secret";
            value: string;
        };
        NEXTAUTH_SECRET: {
            type: "sst.sst.Secret";
            value: string;
        };
        NEXTAUTH_URL: {
            type: "sst.sst.Secret";
            value: string;
        };
        S3_ACCESS_KEY: {
            type: "sst.sst.Secret";
            value: string;
        };
        S3_ENDPOINT: {
            type: "sst.sst.Secret";
            value: string;
        };
        S3_SECRET_KEY: {
            type: "sst.sst.Secret";
            value: string;
        };
        S3_BUCKET: {
            type: "sst.sst.Secret";
            value: string;
        };
        "mikn-dev": {
            type: "sst.aws.Nextjs";
            url: string;
        };
    }
}
