main = ".worker-next/index.mjs"
name = "mikn-dev"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }
minify=true

[observability]
enabled = true