main = ".open-next/worker.js"
name = "mikn-dev"
compatibility_date = "2025-03-04"
compatibility_flags = ["nodejs_compat"]
assets = { directory = ".worker-next/assets", binding = "ASSETS" }

[[kv_namespaces]]
binding = "NEXT_CACHE_WORKERS_KV"
id = "914f30b5215d4d3c9dbae19952e042c5"