import {
  Mic,
  KeyRound,
  Link2Off,
  Download,
  Calculator,
  Rss,
  Camera,
  BadgeCheck,
  MemoryStick,
  Gamepad2,
  Code,
  Webhook,
  Bot,
  AppWindow,
  Wrench,
  FlaskConical,
  Skull,
} from "lucide-react";
import { Solution, Categories, CategoryMeta } from "@/types/solutions";

export const CategoryMetadata: Record<Categories, CategoryMeta> = {
  [Categories.GAMES]: { name: "solutions.categories.games", icon: Gamepad2 },
  [Categories.DEVTOOLS]: { name: "solutions.categories.devtools", icon: Code },
  [Categories.APIS]: { name: "solutions.categories.apis", icon: Webhook },
  [Categories.BOTS]: { name: "solutions.categories.bots", icon: Bot },
  [Categories.APPS]: { name: "solutions.categories.apps", icon: AppWindow },
  [Categories.UTILITIES]: {
    name: "solutions.categories.utilities",
    icon: Wrench,
  },
  [Categories.BETA]: { name: "solutions.categories.beta", icon: FlaskConical },
  [Categories.DEAD]: { name: "solutions.categories.dead", icon: Skull },
};

export const SolutionList: Solution[] = [
  {
    slug: "karasnap",
    name: "solutions.karaSnap.title",
    description: "solutions.karaSnap.description",
    icon: Mic,
    source: "https://github.com/mikndotdev/karasnap",
    url: "https://karasnap.mikn.dev",
    categories: [Categories.APPS],
  },
  {
    slug: "next-discord-auth",
    name: "solutions.nextDiscordAuth.title",
    description: "solutions.nextDiscordAuth.description",
    icon: KeyRound,
    source: "https://github.com/mikndotdev/next-discord-auth",
    url: "https://npm.im/@mikandev/next-discord-auth",
    categories: [Categories.DEVTOOLS, Categories.APIS],
  },
  {
    slug: "sibuster",
    name: "solutions.siBuster.title",
    description: "solutions.siBuster.description",
    icon: Link2Off,
    source: "https://github.com/mikndotdev/sibuster",
    url: "https://mikn.dev/solutions/sibuster",
    categories: [Categories.UTILITIES],
  },
  {
    slug: "releaselink",
    name: "solutions.releaselink.title",
    description: "solutions.releaselink.description",
    icon: Download,
    source: "https://github.com/mikndotdev/releaselink",
    url: "https://mikn.dev/solutions/releaselink",
    categories: [Categories.DEVTOOLS, Categories.UTILITIES],
  },
  {
    slug: "100masu",
    name: "solutions.100masu.title",
    description: "solutions.100masu.description",
    icon: Calculator,
    source: "https://github.com/mikndotdev/100masu",
    url: "https://mikn.dev/solutions/100masu",
    categories: [Categories.GAMES],
  },
  {
    slug: "rssfetch",
    name: "solutions.rssfetch.title",
    description: "solutions.rssfetch.description",
    icon: Rss,
    source: "https://github.com/mikndotdev/rssfetch",
    url: "https://mikn.dev/solutions/rssfetch",
    categories: [Categories.APIS, Categories.DEVTOOLS],
  },
  {
    slug: "sukushocloud",
    name: "solutions.sukushocloud.title",
    description: "solutions.sukushocloud.description",
    icon: Camera,
    source: "https://github.com/mikndotdev/sukushocloud",
    url: "https://sukusho.cloud",
    categories: [Categories.APPS, Categories.UTILITIES],
  },
  {
    slug: "enkabadges",
    name: "solutions.enkabadges.title",
    description: "solutions.enkabadges.description",
    icon: BadgeCheck,
    source: "https://github.com/mikndotdev/enkabadges",
    url: "https://mikn.dev/solutions/enkabadges",
    categories: [Categories.APIS, Categories.UTILITIES],
  },
  {
    slug: "sd2immich",
    name: "solutions.sd2immich.title",
    description: "solutions.sd2immich.description",
    icon: MemoryStick,
    source: "https://github.com/mikndotdev/sd2immich",
    url: "https://mikn.dev/solutions/sd2immich",
    categories: [Categories.APPS, Categories.UTILITIES],
  },
];
