import type { Metadata } from "next";
import { headers } from "next/headers";
import { Providers } from "./providers";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang={headers().get("x-locale")?.split("-")[0]} className='dark'>
            <body>
                <Providers>{children}</Providers>
            </body>
        </html>
    );
}
