import type { Metadata } from "next";
import { headers } from "next/headers";
import localFont from 'next/font/local'
import "./globals.css";

const hsr = localFont({ src: './assets/ja-JP.woff2' })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html className={hsr.className} lang={headers().get("x-locale")?.split("-")[0]}>
            <body>{children}</body>
        </html>
    );
}
